cbg-ethz/V-pipe

README.md
Another suggestion : Links to authors.
In this exemple I'm using your ORCIDs.
Of course, other URLs could be used I you prefer.
=> Author links

README.md
SEO through link-farming :
- badge to framework used (snakemake)
- badge to repositories listing (bio.tools, omictools)
- badge with google-analytics beacon
=> a little bit of SEO

_includes/flashNews.html, assets/main.scss, index.md
A news "FlashNews" box include-script
- used for BASEL LIFE 2019
=> Flash News box

index.md
The next conference in the newsflash
=> Newsflash: next upcoming conference

2_sars-cov-2.md, _includes/flashNews.html, assets/main.scss, index.md
Pre-announcement with:
- Red alert box
- Place-holder page, that already has "subscribe" call to action so people will get informed of the release of the version.
=> SARS-CoV-2 version pre-announcement

envs/bowtie_align.yaml, envs/bwa_QA.yaml, envs/bwa_align.yaml, envs/convert_to_ref.yaml, envs/haploclique.yaml, envs/hmm_align.yaml, envs/initial_vicuna.yaml, envs/initial_vicuna_msa.yaml, envs/lofreq.yaml, envs/msa.yaml, envs/preprocessing.yaml, envs/sam2bam.yaml, envs/savage.yaml, envs/smallgenomeutilities.yaml, envs/snv.yaml
This PR proposes two changes:
* Reorder conda environments to recommended order (conda-forge, bioconda, defaults)
* Remove deprecated r channel
=> Improve conda environments

assets/main.scss, tutorial_sarscov2.md
- make table scrollable on mobile (keep google search happy)
- snakemake has change the `--conda-create-envs-only` command
=> fixes in tutorial

rules/common.smk, rules/visualization.smk, scripts/assemble_visualization_webpage.py
This PR adds some more fixes and features to the already existing visualization.
=> Visualization fixes and features

rules/visualization.smk, scripts/assemble_visualization_webpage.py, scripts/visualization.html
This PR only contains UI improvements + fixes the bug with the coverage plot. 
Next will come: adding primers, protein 3D structure and phylogenetic tree.
=> Improve visualisation 

3_literature.md, _includes/literature-components.html, _includes/literature-general.html, _includes/literature-primary.html, _literature/HOWTO.md, _literature/components.bib, _literature/general.bib, _literature/primary.bib, assets/main.scss, tutorial_sarscov2.md
=> updates in Literature page

envs/visualization.yaml, references/metainfo.yaml, rules/clean.smk, rules/common.smk, rules/visualization.smk, scripts/assemble_visualization_webpage.py, scripts/visualization.html, vpipe.config
- handles absent GFF or primers gracefully
- same reference as SNVs (cohort consensus instead of reference)
- (minor cosmetic)
=> visualisation fixes

envs/sratools.yaml, scripts/download.py, vpipeFetch.config.yaml, vpipeFetch.smk
This PR supersedes #44 and provides a rebased, more robust experience.
=> Add SRA download functionality (vpipeFetch)

envs/predicthaplo.yaml, rules/align.smk, rules/clean.smk, rules/common.smk, rules/config_default.smk, rules/haplotypes.smk
This PR adds [PredictHaplo](https://github.com/cbg-ethz/PredictHaplo) to V-pipe.
Warning: PredictHaplo is prone to crashing, so further tests have to be conducted.
=> Add PredictHaplo for global haplotype reconstruction

envs/bcftools.yaml, rules/common.smk, rules/config_default.smk, rules/consensus.smk, scripts/enhance_bcf.py, vpipe.snake
=> Add ability to create consensus sequences using bcftools

rules/common.smk, scripts/assemble_visualization_webpage.py
This PR fixes the variant frequency computation for variants called with LoFreq.
=> Fix visualization of variants called with LoFreq

Dockerfile, config/config.yaml, tests/regression_tests.sh, workflow/Snakefile, workflow/envs/diversity_measures.yaml, workflow/rules/common.smk, workflow/rules/diversity_measures.smk, workflow/schemas/config_schema.json, workflow/scripts/aggregate_diversity.py, workflow/scripts/compute_diversity_measures.py
This PR consists of a new feature that is computing a selection of diversity indices based on SNVs. It should be ready to merge.
=> Feature diversity measures

workflow/rules/haplotypes.smk
- predicthaplo segfaults if the output directory doesn't exist.
=> PredictHaplo fix ouput directory

README.md
This PR aims to clarify how publications can be added to our webpage.
=> Enhancing Docs for Adding Publications

getting-started.md
This pull request suggests a typo and minor wording suggestion in getting-started.md.
=> Typo and Minor Wording Suggestion in getting-started.md

README.md
Resolves: 
- https://github.com/cbg-ethz/virus-private/issues/12
=> docs: minor rewording of adding events instructions
